config/routes.rb
Rails.application.routes.draw do
  
  resources :tasks do
      member do
          get :flop 
      end
  end
  
  resources :tasks
  get 'pages/index'

  root 'tasks#index'

end

app/models/task.rb
# Defines and validates tasks
class Task < ActiveRecord::Base

	before_save :default_values
	# Sets default values for done
	def default_values
		self.done ||= 'false'
		self.flag ||= 'false'
	end
	validates :title, presence: true 
	validates :description, length: {maximum: 560}
end

app/controllers/application_controller.rb
# Prevents CSRF attacks be raising an exception
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
end

app/controllers/pages_controller.rb
# Allows root to be set
class PagesController < ApplicationController
  
  # Provides class for setting the root
  def index
  end

end

app/controllers/tasks_controller.rb
# Actions that can be done to a task
class TasksController < ApplicationController
helper_method :sort_column, :sort_direction

	# Changes the boolean "done" when the done button is clicked
	def flop 
		@tasks = Task.find(params[:id])
		@tasks.done = !@tasks.done
		@tasks.save
		redirect_to tasks_path
	end

	# Empty method for new task (placeholder)
	def new
	end

	# Shows task
	def show
		@task = Task.find(params[:id])
	end 

	# Calls helper functions that will sort tasks by various parameters
	def index
		@tasks = Task.order(sort_column + " " + sort_direction)

	end

	# Creates a new task if the sumbit button is clicked, or goes back to the tasks if 'back' is clicked
	def create 
		#render plain: params[:task].inspect
		@task = Task.new(task_params)
		if @task.save
			redirect_to @task
		else
			render 'new'
		end  
	end

	# Deletes a task
	def destroy 
		@task = Task.find(params[:id])
		@task.destroy
		redirect_to tasks_path
	end

	# Creates a new task with the current parameters filled in and deletes old task. Form will be filled in when that screen comes up.
	def edit
		@task = Task.find(params[:id])
		@task.destroy
	end

	private 

		# Parameters for the tasks (not all used)
		def task_params
			params.require(:task).permit(:title, :description, :priority, :category, :due,
				:start, :timelength, :reward, :autopriority, :done)
		end

		# Variable for the helper functions to use (for sorting)
		def sort_column
			Task.column_names.include?(params[:sort]) ? params[:sort] : "title"
		end

		# Another variable for the sorting helper function
		def sort_direction
			%w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
		end
end

app/helpers/application_helper.rb
# Helper functions for application_controller
module ApplicationHelper
	# Sorts the tasks by column in either ascending or descending order
	def sortable(column, title = nil)
	  title ||= column.titleize
	  direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
	  link_to title, {:sort => column, :direction => direction}
	end
end

app/helpers/pages_helper.rb
# Helper functions for pages_controller
module PagesHelper
end

app/helpers/tasks_helper.rb
# Helper function for tasks_controller
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <link href="/assets/bootstrap.css?body=1" media="screen" rel="stylesheet">
  <link href="/assets/custom.css?body=1" media="screen" rel="stylesheet">
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %> 
  <title>AntiProcrastination</title>
</head>
<body>
<%= render 'header' %>
<%= yield %>
<%= render 'footer' %>

</body>
</html>

app/views/pages/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AntiProcrastination</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>


<h1> AntiProcrastination App </h1>
<%= link_to 'View Current Tasks', controller: 'tasks' %>
<br>
<%= link_to 'Add a task', new_task_path %>
<%= yield %>

app/views/tasks/_header.html.erb
<nav role="navigation" class="navbar navbar-default">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
        <button type="button" data-target="#navbarCollapse" data-toggle="collapse" class="navbar-toggle">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a href="/" class="navbar-brand active">AntiProcrastinationApp</a>
    </div>
    <!-- Collection of nav links and other content for toggling -->
    <div id="navbarCollapse" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
            <li><a href="/">Tasks</a></li>
            <li><a href="/tasks/new">Create Task</a></li>
            <li><a href="#">GitHub</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
            <li><a href="#">Login</a></li>
        </ul>
    </div>
</nav>

app/views/tasks/destroy.html.erb
<h>Task destroyed</h>

<%= link_to 'Back', tasks_path %>

app/views/tasks/edit.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AntiProcrastination</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" type="text/css" href="style.css">
</head>
<body>

<h1> Edit Task </h1>
<%= form_for :task, url: tasks_path do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :category %><br>
    <%= f.select(:category, options_for_select(["Social","Work"]))%>
  </p>

  <p>
    <%= f.label :text %><br>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.label :due %><br>
    <%= f.datetime_select( :due, :ampm=> true, :minute_step => 15) %>
  </p>

  <p>
    <%=f.label :priority %><br>
    <%= f.select(:priority, options_for_select([["High", 1],["Medium",2],["Low",3]]))%>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>
</body>

app/views/tasks/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AntiProcrastinationApp</title>
</head>
<body>

<div class="center"><h1>  Today is <%= Time.now.strftime("%A, %B %d") %>. </h1> </div>

<div class="createt"><%= link_to 'Create Task', new_task_path%></div>
 
  <!-- Sorting mechanisms.  Use helper functions. -->
  <div class="sorts">
     <%= sortable "title"%> 
     <%= sortable "due"%> 
     <%= sortable "priority"%> 
     <%= sortable "created_at", "Created"%>
     <%= sortable "done", "Finished" %>
  </div>


  <% @tasks.each do |t| %>
    <!-- Displays all pending tasks -->
    <% if t.done == false %>      
      <% due_adjusted = (t.due.to_time + 6.hours).to_datetime %>
      <!--Change task color to red if it is past due date -->
      <% if Time.zone.now > due_adjusted %><div class="square4">
      <% else %>

      <!-- Colors task square according to priority -->
      <% if t.priority == 1%><div class="square1"><% end %><% if t.priority == 2%><div class="square2"><%end %><% if t.priority == 3%><div class="square3"><% end %> 
      <% end %>

      <div class="title"><%= t.title %></div>
      <div class="description"><%= t.description%></div>
      <div class="details">
      <!-- Priority is mapped to numbers 1,2,3.  -->
      Priority: <% if t.priority == 1%>High<% end %><% if t.priority == 2%>Medium<%end %><% if t.priority == 3%>Low<% end %> <br>
      <!-- Difference between now and when created in words -->
      Created or edited <%= distance_of_time_in_words(t.created_at, Time.now) %> ago. <br>
      <!-- Due date  -->
      Complete before <%= t.due.strftime("%A %m/%d at %I:%M%p") %> <br>

      <%= link_to 'Edit', edit_task_path(t) %>
      <%= link_to 'Delete', task_path(t), method: :delete %>
      <%= link_to 'Done', flop_task_path(t) %>
      </div>
     </div>
    <% end %>
  <% end %>
  <% if @tasks.count == 0 %>
    <div class="center"> <h3> No Pending Tasks! :) </h3></div>
  <% end %>

  <!-- Trying to figure out a way to check if there is more than 1 finished tasks
  <% if @tasks.count > 0 %>
    <span> <div class="center1"> <h3> Finished: </h3> </div> </span>
  <% end %>
  -->

  <!-- This block is used to display finished Tasks. -->   
  <% @tasks.each do |t| %>
    <% if t.done == true%>
      <div class="squareDone"> 
        <div class="title"><%= t.title %><div class="details">has been completed.
        <%= link_to 'Delete', task_path(t), method: :delete %>
        </div>

      </div>
      </div>
    <% end %>
   <% end %>

</body>

app/views/tasks/new.html.erb
<div class="container">
<h1> New Task </h1>

<%= form_for :task, url: tasks_path do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_area :title, :cols => "29", :rows => "1"%>
  </p>

  <p>
    <%= f.label :category %><br>
    <%= f.select(:category, options_for_select(["Social","Work"]))%>
  </p>
 
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description, :cols => "29", :rows => "5" %>
  </p>

  <p>
    <%= f.label :due %><br>
    <%= f.datetime_select( :due, :ampm=> true, :minute_step => 15 )%>
  </p>

  <p>
    <%=f.label :priority %><br>
    <%= f.select(:priority, options_for_select([["High", 1],["Medium",2],["Low",3]]))%>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>
<%= link_to 'Back', tasks_path %>
</div>

app/views/tasks/show.html.erb
<body>

<p> 
  <strong>Task: </strong>
  <%= @task.title %> 
</p>

<p>
  <strong>Category: </strong>
  <%= @task.category %>
</p>

<p>
  <strong> Description: </strong>
  <%= @task.description %> 
</p>

<p>
  <strong> Due Date: </strong>
  <%= @task.due.strftime("%I:%M on %A %m-%d-%Y") %><br>
</p>

<p>
  <strong> Priority: </strong>
  <% if @task.priority == 1%>
	High
  <% end %>
  <% if @task.priority == 2%>
	Medium
  <% end %>
  <% if @task.priority == 3%>
	Low
  <% end %>

</p>

<%= link_to 'Back', tasks_path %>

</body>